### ISSUE TITLE
subdirectory support?

### ISSUE THREAD

**Issue by wdan** [HKUST-VISLab/vismooc-wiki#2]
It seems that github wiki doesn't support to access `wiki/SUB_DIRECTORY/A.md`. It works well if we put `A.md` under `wiki/`.

It is better if we can put `October-2016-Plan.md` under a subfolder named `Plans`

**Comment by chenzhutian** [comment]
http://stackoverflow.com/questions/14408376/how-can-you-use-subdirectories-in-a-github-wiki-checkout

Github wiki does not support  subfolder structure. All markdown files are flat. We can name files followed name convention to achieve hierarchy structure.

I find out that vscode team uses issues with "iteration plan" label to document their iteration plan, e.g. [here](https://github.com/Microsoft/vscode/issues/11917). The advantages of recording iteration plan in this way are, for example, that others can comment on the plan and the plan can be referenced in other issues.

What do you think?

**Comment by chenzhutian** [comment]
Oh I see the problem. Their iteration plan only aims at one repository, but ours is for different repositories.

**Comment by wdan** [comment]
@chenzhutian Yes, I also saw that the vscode team use the issue pages. We can also use the issue pages of `vismooc-wiki`. However, this would bind us to Github. I'd prefer to use `.md` files so that we are able to export our records to other platforms in the future. In this case, we use name conventions for the hierarchy structure.
